apiVersion: v1
kind: ConfigMap
metadata:
  name: config
data:
  appsettings.Development.json: |
    {
      "Logging": {
        "LogLevel": {
          "Default": "Information",
          "Microsoft.AspNetCore": "Warning",
          "DemoWebApplication.Services.OpenshiftFileWatcherService": "Debug"
        }
      },
      "OTLP_ENDPOINT_URL": "http://localhost:4317/",
      "OpenShift": {
        "EdgeTermination": false
      },
      "Certificate": {
        "Path": "/app/certs/dev-server.pfx",
        "Password": "productionpass456",
        "Port": 8443,
        "Enabled": true
      }
    }
