apiVersion: v1
kind: ConfigMap
metadata:
  name: config
  labels:
    app: myapi
data:
  appsettings.Production.json: |
    {
      "Logging": {
        "LogLevel": {
          "Default": "Debug",
          "Microsoft.AspNetCore": "Warning",
          "DemoWebApplication.Services.OpenshiftFileWatcherService": "Debug"
        },
        "Console": {
          "FormatterName": "simple",
          "FormatterOptions": {
            "SingleLine": true,
            "IncludeScopes": true,
            "TimestampFormat": "yyyy-MM-dd HH:mm:ss ",
            "UseUtcTimestamp": false
          }
        }
      },
      "AllowedHosts": "*",
      "OTLP_ENDPOINT_URL": "http://jaeger-collector:14268/api/traces",
      "Certificate": {
        "Path": "/app/certs/dev-server.pfx",
        "Password": "devpassword",
        "Port": 8443,
        "Enabled": true
      }
    }
