apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: myapi-base

resources:
- deployment.yaml
- service.yaml
- configmap.yaml
- serviceaccount.yaml
- tls-secret.yaml

commonLabels:
  app: myapi
  component: api

namePrefix: myapi-

images:
- name: myapi
  newTag: latest

replicas:
- name: deployment
  count: 1
